# docker-compose.prod.yml
version: "3.9"

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind  0.0.0.0:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
