# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/myproject:${{ github.sha }}
          secrets: |
            MY_SECRET=${{ secrets.MY_SECRET }}
      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Deploy to dev environment"
          # Add deployment commands here
      - name: Deploy to Prod
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploy to production environment"
          # Add deployment commands here
